#!/usr/bin/env bash
##
## Copyright 2014-2025 Real Logic Limited.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## https://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##

source ./script-common

function startClient() {
    ${JAVA_HOME}/bin/java \
        -cp ../../../aeron-all/build/libs/aeron-all-${VERSION}.jar \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+TrustFinalNonStaticFields \
        -XX:+UnlockDiagnosticVMOptions \
        -XX:GuaranteedSafepointInterval=300000 \
        -XX:+UseParallelGC \
        -Daeron.cluster.hydra.accountId="${1}" \
        -Daeron.cluster.hydra.commandCount="${2}" \
        ${JVM_OPTS} ${ADD_OPENS} \
        io.aeron.samples.cluster.hydra.HydraExchangeClient
}

ACCOUNT_ID=${1:-42}
COMMAND_COUNT=${2:-12}

startClient ${ACCOUNT_ID} ${COMMAND_COUNT}
